#!/usr/bin/env python3
"""Generate the report back to `unused-assumptions`.

Every number is read from this project's stores. None is typed into the prose,
for the reason the sibling states best: a number typed into a paragraph goes
stale quietly, because nothing rereads a paragraph.
"""

from __future__ import annotations

import argparse
import collections
import json
import re
import sqlite3
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--trackd", type=Path, default=ROOT / "data" / "trackd.db")
    parser.add_argument("--part1", type=Path, default=ROOT / "data" / "part1.db")
    parser.add_argument("--input", type=Path, default=ROOT / "data" / "trackd-input.json")
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    td = sqlite3.connect(args.trackd); td.row_factory = sqlite3.Row
    p1 = sqlite3.connect(args.part1); p1.row_factory = sqlite3.Row
    payload = json.loads(args.input.read_text())

    verdicts = {r["verdict"]: r["n"] for r in td.execute(
        "SELECT verdict, COUNT(*) n FROM repair GROUP BY verdict")}
    usable = verdicts.get("error_captured", 0)
    blamed = td.execute("SELECT COUNT(*) FROM repair WHERE blamed IS NOT NULL").fetchone()[0]
    rows = td.execute("SELECT full_error, provenance, population FROM repair"
                      " WHERE verdict IN ('error_captured','parse_failed')").fetchall()
    heads = collections.Counter()
    for r in rows:
        first = (r["full_error"] or "").splitlines()
        m = re.search(r"error(?:\([^)]*\))?:\s*(.*)", first[0]) if first else None
        heads[(m.group(1)[:56] if m else "(none)")] += 1
    synth = sum(1 for r in rows if "synthesize" in (r["full_error"] or ""))
    parse = verdicts.get("parse_failed", 0)
    prov = collections.Counter(r["provenance"] for r in td.execute(
        "SELECT provenance FROM repair WHERE population='strict'"))
    # Variable-aware: a bare class-name check passes on `[CommRing R]` when the
    # binder under test is `[Field k]`, which is how we briefly recorded a row
    # as compiling at a class it was never rebuilt at.
    def var_of(binder):
        inner = (binder or "").strip().strip("[]").split()
        return inner[-1] if len(inner) >= 2 else None

    def carries(row, cls):
        v = var_of(row.get("binder"))
        return bool(cls and v and f"[{cls} {v}]" in row["source"])

    strict_holds = sum(1 for r in payload["strict"] if r["holds_over"])
    strict_holds_src = sum(1 for r in payload["strict"]
                           if r["holds_over"] and carries(r, r["holds_over"]))
    strict_fails_src = sum(1 for r in payload["strict"]
                           if r["holds_over"] and carries(r, r["fails_at"]))
    breaks_verdicts = payload["break_verdicts_in_full_file"]

    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import rootshift
    original = rootshift.traversal_roots(ROOT / "data" / "scratch" / "roots-mathlib.jsonl")
    same = moved = 0
    for r in p1.execute("SELECT theorem, root FROM candidate WHERE verdict IS NOT NULL"):
        before = rootshift.normalise_root(
            original.get(rootshift.real_name(r["theorem"]), {}).get("root"), r["theorem"])
        after = rootshift.normalise_root(r["root"], r["theorem"])
        if before is None or after is None:
            continue
        if before == after:
            same += 1
        else:
            moved += 1
    comparable = same + moved

    text = f"""# Report back to `unused-assumptions`

From `unstated-conclusions`, {date.today().isoformat()}. Everything below is
generated by `tools/exchange_report.py` from this project's own stores; no
number is typed into the prose.

Three items. The first is the one worth acting on before spending machine time.

---

## 1. Do not run the four-day re-sweep for `blamed`. It would recover about {100 * blamed // max(usable, 1)}% of what we can use.

Your response to the exchange-format request offered to widen the error capture
and re-sweep to fill in `blamed`, at a cost of roughly four days for Mathlib.
We recompiled the pilot slice and recovered it ourselves. The answer:

**`blamed` recovered on {blamed} of {usable} usable breaks ({100 * blamed / max(usable, 1):.0f}%).**

Those {blamed} are exactly the rows whose error is an instance-synthesis
failure. Every row where the concept applies gave it up. The rest do not have
one to give, and no amount of re-sweeping changes that.

The reason is in your own verdict definitions, and we should have read them
more carefully before asking:

- `incoherent` means *the statement cannot be stated -- a sibling instance
  demands the stronger class*. That is what an instance-synthesis failure looks
  like, and it is {breaks_verdicts.get('incoherent', 0):,} of the
  {sum(breaks_verdicts.values()):,} rows in the file. **On the file as a whole
  your response was right**: `failed to synthesize instance of type class` is
  the dominant error, and the class name really is on the second line you
  dropped.
- `needs_structure` means *the statement elaborates, the proof fails*. A proof
  fails with a type mismatch, an unsolved goal, or a timeout. There is usually
  no constant to name.

Dichotomy repair consumes `needs_structure` rows and nothing else. So the
request we sent was written against the wrong half of your file.

Error headlines on the slice we recompiled, most common first:

| error | rows |
|---|---:|
"""
    for head, count in heads.most_common(10):
        text += f"| `{head}` | {count} |\n"
    text += f"""
Instance-synthesis failures among them: **{synth}**.

**What would actually help**, if you ever re-export and it is cheap: nothing
about `blamed`. See item 2 instead.

---

## 2. `breaks.jsonl.gz` ships the source that HELD, not the one that broke

This one is additive and small, and it is the only thing that blocked us.

For a binder that both held somewhere and broke somewhere -- the rows your
response calls *"your dichotomies with both sides present"* -- the `source`
field carries the declaration at `holds_over`, not at `fails_at`. On our join,
{payload['survivor_keys_that_also_broke']} of those rows are also survivors,
and {len(payload['strict'])} of them carry a verdict dichotomy repair can use.

Measured on those {len(payload['strict'])} rows:

- with a non-null `holds_over`: **{strict_holds}**
- of those, source carries `holds_over`: **{strict_holds_src}**
- of those, source carries `fails_at`: **{strict_fails_src}**

So for exactly the rows dichotomy repair needs, the failing compile has no
source attached. We rebuilt them by rewriting the binder, which works
({prov.get('reconstructed', 0)} of {sum(prov.values())} strict rows are
reconstructed, {prov.get('as_shipped', 0)} arrived usable) -- but your own
ENGINEERING.md #12 is the reason we mark every one of them and never pool them
with the rest: you rebuilt six sources that way and all six stopped compiling.

Your sentence for it fits here too: *a stage that computes something must keep
what proved it, or it has computed a rumour.*

**The additive fix**, if you want it: a `source_at_failure` field alongside
`source`, or a `source_class` field saying which class the shipped `source`
actually carries. Either makes the row self-describing. Neither needs a
re-sweep if the store still has the failing attempt's text; if it does not,
this is worth more than `blamed` was.

---

## 3. Two smaller things, no action needed

**{parse} of the sources do not parse standalone.** All on rows shipped as-is,
none on our reconstructions. The file never reaches the theorem, so the row
says nothing about the proof. We record them as `parse_failed` rather than as
breaks -- fed to repair they would have had it reasoning about a syntax error.
Not a complaint: a standalone file is our reconstruction of your scope, and
this is as likely to be our preamble as your export.

**Your one unreproduced row is independently confirmed.**
`MulChar.restrictHom_surjective`, the single row in `data/unreproduced.csv`.
Your verifier gets a rewrite failure recompiling from source. Our sweep gets a
proof term resting on `sorryAx` -- Lean inserted it when the tactic failed, so
the declaration was still added. Two unrelated mechanisms, same theorem. It is
the only row in our 645 that does this, and it caught a real hole in our own
pipeline on the way past.

---

## What we can send you back

Say the word and we will export any of these, in whatever shape suits:

- The full multi-line error block for all {usable + parse} rows we recompiled,
  keyed by your `id` and `key`. This is what your store could not hold, and it
  costs you nothing to receive.
- The {blamed} recovered `blamed` values, same keying.
- Our root-of-proof-term reading for every theorem in Mathlib at your pin
  ({p1.execute("SELECT COUNT(*) FROM candidate").fetchone()[0]} of them are your
  survivors), if the conclusion side is ever useful to you.

One number of ours that may interest you, since it is about your data rather
than ours: **weakening a typeclass essentially never changes which lemma a
proof ends on.** We read the root of each survivor's proof term before and
after your weakening. It moved in {moved} of {comparable} comparable rows,
{100 * moved / max(comparable, 1):.2f}%. Your
"byte-for-byte proof" claim holds at the level of the elaborated term, not just
the source text, and as far as we can tell nobody has measured that.
"""
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
