#!/usr/bin/env python3
"""Describe Track D's two populations. Generated; nothing here is typed.

The two are never merged and the file says why in its own caption. A rate over
the top-up is not a rung-3 rate, and the only defence against that sentence
being dropped later is to generate it beside the numbers it qualifies.
"""

from __future__ import annotations

import argparse
import collections
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# What the weakened-past-the-break class says the exceptional region is. Hand
# written, and short on purpose: an entry that guesses wrong here mislabels a
# row in a document a person reads, which is recoverable. An entry that guesses
# wrong in weakenings.json silently reports no slack, which is not.
EXCEPTIONAL = {
    "Nontrivial": "the trivial ring (`Subsingleton`)",
    "CommRing": "elements that are not units / zero divisors",
    "DivisionRing": "failure of commutativity",
    "Monoid": "failure of commutativity",
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=ROOT / "data" / "trackd-input.json")
    parser.add_argument("--brother", type=Path, default=ROOT.parent / "unused-assumptions")
    parser.add_argument("--out", type=Path, default=ROOT / "docs" / "trackd-input.md")
    args = parser.parse_args()

    print(f"# read {args.input}", file=sys.stderr)
    data = json.loads(args.input.read_text())
    survivors = {r["key"]: r for r in
                 (json.loads(line) for line in
                  (args.brother / "data" / "survivors.jsonl").read_text().splitlines()
                  if line.strip())}

    rows = []
    for row in data["strict"]:
        survivor = survivors[row["key"]]
        rows.append({
            "theorem": row["theorem"], "area": row["area"],
            "stated": survivor["stated"], "held": survivor["holds_over"],
            "broke": row["fails_at"], "error": row["fail_error"],
            "case": EXCEPTIONAL.get(row["fails_at"], "?"),
        })
    cases = collections.Counter(r["case"] for r in rows)

    out = ["# Track D's input\n",
           "Generated by `tools/trackd_report.py` from `data/trackd-input.json`. "
           "Every count here is read from the sibling's export; none is typed.\n",
           "## Two populations, never merged\n",
           f"**Strict (rung 3): {data['population_strict']['rows']} rows.** "
           f"{data['population_strict']['what']}. Joined on "
           f"`{data['population_strict']['join']}`.\n",
           f"**Top-up: {data['population_topup']['rows']} rows** drawn from a pool of "
           f"{data['population_topup']['pool']}, seed {data['population_topup']['seed']}. "
           f"{data['population_topup']['what']}\n",
           "## Why the strict population is ten and not two hundred\n",
           f"`BRIEF.md` budgets Part 1's pilot at roughly two hundred candidates drawn "
           f"from the survivors' own rows in `breaks.jsonl.gz`. Joining the two files on "
           f"`key` gives {data['survivor_keys_that_also_broke']} rows: binders that both "
           f"held somewhere and broke somewhere, which is the rung-3 shape.\n",
           f"{data['of_those_not_repairable']} of them broke with the verdict "
           f"`incoherent`, which the sibling's own `docs/pipeline.md` defines as *the "
           f"statement cannot be stated -- a sibling instance demands the stronger "
           f"class*. Track D's target is `a'' -> b \\/ c`, which needs an `a''` the "
           f"statement can be written over. An incoherent break cannot carry one.\n",
           "That is the sibling's definition of its own verdict, not a judgement made "
           "here. Ten rows remain.\n",
           "## The ten\n",
           "| theorem | area | stated | held at | broke at | exceptional case |",
           "|---|---|---|---|---|---|"]
    for r in sorted(rows, key=lambda r: (r["case"], r["theorem"])):
        out.append(f"| `{r['theorem']}` | {r['area']} | `{r['stated']}` | "
                   f"`{r['held']}` | `{r['broke']}` | {r['case']} |")
    out.append("\n## What the shapes say before any prover runs\n")
    for case, count in cases.most_common():
        out.append(f"- **{count}**: {case}")
    out.append("")
    out.append("`BRIEF.md` names the first of these in advance as the outcome that "
               "means the track produced a linter for degenerate-case clauses rather "
               "than theorems. It is the largest group here. The pilot is sized to "
               "detect that cheaply, not to avoid it.\n")
    out.append("One row deserves flagging before it is run: "
               "`LinearIndependent.of_subsingleton` is a theorem about subsingletons "
               "whose exceptional case is `Subsingleton`. Expect `restatement`.\n")
    out.append("## Fields that are not what they look like\n")
    out.append("- `blamed` is null on all 57,382 rows of the export and will stay so. "
               "The sweep kept only the first error line and Lean puts the class name "
               "on the second. The split property is derived from the class pair.\n")
    out.append("- `fails_at` is the sibling's *reconstruction*: its table proposes "
               "several classes per binder and tries each independently, so \"the "
               "first class below\" is not a recorded event. `descent` carries every "
               "class tried, and this project recomputes the break point under its own "
               "order.\n")
    out.append("- `fail_error` is capped at 200 characters by the store. There is no "
               "more to give without a four-day re-sweep.\n")
    out.append("- `context` rows are the sibling's tooling failing to reconstruct "
               "scope, not a fact about any theorem. Excluded from both populations as "
               "missing data.\n")
    args.out.write_text("\n".join(out) + "\n")
    print(f"wrote {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
